version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 8081:8081
    volumes:
      - ./:/code
  mongo-container:
    image: mongo:latest
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=123456
        # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        # Here you are setting the username and password
        # so change it to whatever you want
        # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    volumes:
        - ./data:/data/db
    ports:
      - "27017:27017"
    command: mongod
